apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tb6l5ea0q-python 
  janus-idp.io/tekton: tb6l5ea0q-python
  backstage.io/kubernetes-id: tb6l5ea0q-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tb6l5ea0q-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  